name: Github Pages Deploy
on:
  push:
    branches:
      - master
jobs:
  update-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install dependency
      run: |
        npm install
    
    - name: Update JSON
      run: |
        npm run update-api

    - name: Commit and Push changes
      uses: github-actions-x/commit@v2.4
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        email: action@github.com
        name: GitHub Action
        commit-message: Update by Github Action
    
    - name: Build
      run: |
        npm run export
    
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./__sapper__/export/svelte-instant-game-collection
