name: Github Pages Deploy
on:
  push:
    branches:
      - master
jobs:
  update-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependency
        run: |
          npm install

      - name: Update JSON
        run: |
          npm run update-api

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_options: '--no-verify'
          commit_message: Update API data
          commit_author: Actions <github-actions[bot]@users.noreply.github.com>

      - name: Build
        run: |
          npm run build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build
