name: Github Pages Deploy
on:
  push:
    branches:
      - master
jobs:
  update-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install dependency
      run: |
        npm install
    
    - name: Update JSON
      run: |
        npm run update-api

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: Update API data
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
    - name: Build
      run: |
        npm run export
    
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./__sapper__/export/svelte-instant-game-collection
